// Types + pure selector helpers. All mutable state lives in `./store`.

export type AccountType =
  | "checking"
  | "savings"
  | "credit"
  | "brokerage"
  | "cash"
  | "loan"
  | "mortgage";

export interface Account {
  id: string;
  name: string;
  institution: string;
  type: AccountType;
  balance: number;
  currency: string;
  /** Date on which `balance` was confirmed. Ledger entries never rewrite this anchor. */
  balanceDate?: string;
  /** true for accounts that exist purely to hold a foreign currency */
  isFx?: boolean;
}

export type TxnKind = "income" | "expense" | "transfer" | "trade";

export interface Transaction {
  id: string;
  date: string;
  accountId: string;
  amount: number;
  kind: TxnKind;
  category: string;
  merchant: string;
  notes?: string;
  tags?: string[];
  recurring?: boolean;
  currency?: string;
  /** set when this cash movement was generated by a trade */
  tradeId?: string;
  /** set when generated by a recurring rule */
  ruleId?: string;
}

export type RecurUnit = "day" | "week" | "month";

/** A repeating transaction. Already-generated entries survive cancellation. */
export interface RecurringRule {
  id: string;
  active: boolean;
  every: number;
  unit: RecurUnit;
  startDate: string;
  /** last date already materialised into a transaction */
  lastRun?: string;
  endDate?: string;
  template: {
    accountId: string;
    amount: number;
    kind: TxnKind;
    category: string;
    merchant: string;
    notes?: string;
    currency?: string;
  };
}

export type AssetClass =
  | "stock"
  | "etf"
  | "commodity"
  | "cash"
  | "crypto"
  | "forex"
  | "other";

export interface Holding {
  id: string;
  symbol: string;
  name: string;
  assetClass: AssetClass;
  shares: number;
  /** average cost per share in the asset's own currency */
  avgCost: number;
  /** average cost per share converted to base currency at trade-time rates */
  avgCostBase: number;
  price: number;
  dayChangePct: number;
  sector?: string;
  currency?: string;
  priceUpdatedAt?: string;
  /** realized profit/loss from closed portions, in the asset's currency */
  realized?: number;
  /** realized profit/loss in base currency, including FX gain/loss */
  realizedBase?: number;
  history: { date: string; price: number }[];
}

export interface Trade {
  id: string;
  date: string;
  symbol: string;
  side: "buy" | "sell";
  shares: number;
  price: number;
  fees: number;
  tax?: number;
  accountId: string;
  currency?: string;
  name?: string;
  assetClass?: AssetClass;
  notes?: string;
  /** value of 1 unit of `currency` in `baseCurrency` on the trade date */
  fxRate?: number;
  /** base currency this trade was costed in */
  baseCurrency?: string;
  /** the other side of a currency exchange */
  exchange?: { toAccountId: string; toCurrency: string; toAmount: number };
}

export interface Budget {
  id: string;
  category: string;
  limit: number;
  spent: number;
}

export interface Goal {
  id: string;
  name: string;
  target: number;
  current: number;
  deadline: string;
  monthlyContribution: number;
}

export interface Dividend {
  id: string;
  date: string;
  symbol: string;
  amount: number;
  accountId?: string;
  currency?: string;
  tax?: number;
}

/** Real estate. Valuation history for back-calculated net-worth. */
export interface Property {
  id: string;
  name: string;
  address?: string;
  purchaseDate: string;
  purchasePrice: number;
  fees: number;
  tax: number;
  currentValue: number;
  currency: string;
  linkedMortgageAccountId?: string;
  soldDate?: string;
  soldPrice?: number;
  valuations: { date: string; value: number }[];
  notes?: string;
}

/** Physical assets: vehicles, collectibles, jewelry, etc. */
export interface PhysicalAsset {
  id: string;
  name: string;
  category: string;
  purchaseDate: string;
  purchasePrice: number;
  fees: number;
  tax: number;
  currentValue: number;
  currency: string;
  soldDate?: string;
  soldPrice?: number;
  notes?: string;
}

export interface IncomeSource {
  id: string;
  name: string;
  kind: "salary" | "rental" | "side" | "dividend" | "interest" | "other";
  monthly: number;
  currency: string;
  active: boolean;
}

/** Cached historical prices for one symbol, indexed by ISO date. */
export interface PriceSeries {
  symbol: string;
  currency?: string;
  updatedAt: string;
  points: { date: string; close: number }[];
}

export interface WatchItem {
  symbol: string;
  name: string;
  assetClass: AssetClass;
  currency?: string;
  price?: number;
  dayChangePct?: number;
  history?: { date: string; price: number }[];
}

// ---- currency ----

export type FxMap = Record<string, number> & { __base?: string };
/** Historical rates keyed `CUR:YYYY-MM` -> value of 1 CUR in base. */
export type FxHistory = Record<string, number>;

/** Value of 1 unit of `cur` expressed in the base currency. */
export function rateOf(cur: string | undefined, fx: FxMap, base: string): number {
  if (!cur || cur === base) return 1;
  const r = fx[cur];
  return typeof r === "number" && isFinite(r) && r > 0 ? r : 1;
}

/** Convert an amount into the base currency using live rates. */
export function toBase(
  amount: number,
  cur: string | undefined,
  fx: FxMap,
  base: string,
): number {
  return amount * rateOf(cur, fx, base);
}

export function convert(
  amount: number,
  from: string | undefined,
  to: string,
  fxRates: FxMap,
): number {
  if (!from || from === to) return amount;
  if (fxRates.__base === to) return amount * rateOf(from, fxRates, to);
  const key = `${from}${to}`;
  if (fxRates[key]) return amount * fxRates[key];
  return amount;
}

/** Historical rate for a month, falling back to the live rate. */
export function rateAtMonth(
  cur: string | undefined,
  month: string,
  hist: FxHistory,
  fx: FxMap,
  base: string,
): number {
  if (!cur || cur === base) return 1;
  const h = hist[`${cur}:${month}`];
  if (typeof h === "number" && h > 0) return h;
  return rateOf(cur, fx, base);
}

// ---- derived metrics (pure) ----

export function totalAssets(accounts: Account[], fx: FxMap = {}, base = "USD") {
  return accounts
    .filter((a) => a.balance > 0)
    .reduce((s, a) => s + toBase(a.balance, a.currency, fx, base), 0);
}
export function totalLiabilities(accounts: Account[], fx: FxMap = {}, base = "USD") {
  return -accounts
    .filter((a) => a.balance < 0)
    .reduce((s, a) => s + toBase(a.balance, a.currency, fx, base), 0);
}
export function netWorth(accounts: Account[], fx: FxMap = {}, base = "USD") {
  return totalAssets(accounts, fx, base) - totalLiabilities(accounts, fx, base);
}

/** Account balance at a date, inferred around the confirmed balance anchor. */
export function accountBalanceAt(account: Account, transactions: Transaction[], date: string) {
  const anchor = account.balanceDate ?? new Date().toISOString().slice(0, 10);
  const ledger = transactions.filter((t) => t.accountId === account.id);
  if (date < anchor) {
    return account.balance - ledger
      .filter((t) => t.date > date && t.date <= anchor)
      .reduce((sum, t) => sum + t.amount, 0);
  }
  return account.balance + ledger
    .filter((t) => t.date > anchor && t.date <= date)
    .reduce((sum, t) => sum + t.amount, 0);
}

/** Cash held in currencies other than the base one, valued in base. */
export function currencyPositions(accounts: Account[], fx: FxMap = {}, base = "USD") {
  return accounts
    .filter((a) => a.currency !== base && a.balance !== 0)
    .map((a) => ({
      account: a,
      rate: rateOf(a.currency, fx, base),
      valueBase: toBase(a.balance, a.currency, fx, base),
    }));
}

export function portfolioValue(holdings: Holding[], fx: FxMap = {}, base = "USD") {
  return holdings.reduce((s, h) => s + toBase(h.shares * h.price, h.currency, fx, base), 0);
}
/** Cost basis in base currency, using the FX rate in force at each trade. */
export function portfolioCost(holdings: Holding[]) {
  return holdings.reduce((s, h) => s + h.shares * (h.avgCostBase || h.avgCost), 0);
}
export function propertyValue(properties: Property[], fx: FxMap = {}, base = "USD") {
  return properties
    .filter((p) => !p.soldDate)
    .reduce((s, p) => s + toBase(p.currentValue, p.currency, fx, base), 0);
}
export function physicalValue(assets: PhysicalAsset[], fx: FxMap = {}, base = "USD") {
  return assets
    .filter((a) => !a.soldDate)
    .reduce((s, a) => s + toBase(a.currentValue, a.currency, fx, base), 0);
}

/** Total net worth including holdings, real estate and physical assets. */
export function totalNetWorth(
  accounts: Account[],
  holdings: Holding[],
  properties: Property[],
  physical: PhysicalAsset[],
  fx: FxMap = {},
  base = "USD",
) {
  return (
    netWorth(accounts, fx, base) +
    portfolioValue(holdings, fx, base) +
    propertyValue(properties, fx, base) +
    physicalValue(physical, fx, base)
  );
}

export function monthKey(d: string) {
  return d.slice(0, 7);
}

export function monthlyCashflow(
  transactions: Transaction[],
  fx: FxMap = {},
  base = "USD",
  fxHist: FxHistory = {},
) {
  const map = new Map<string, { income: number; expense: number }>();
  const today = new Date().toISOString().slice(0, 10);
  for (const t of transactions) {
    if (t.kind !== "income" && t.kind !== "expense") continue;
    if (t.date > today) continue;
    const k = monthKey(t.date);
    const cur = map.get(k) ?? { income: 0, expense: 0 };
    const amount = t.amount * rateAtMonth(t.currency, k, fxHist, fx, base);
    if (amount > 0) cur.income += amount;
    else cur.expense += -amount;
    map.set(k, cur);
  }
  return Array.from(map.entries())
    .sort(([a], [b]) => (a < b ? -1 : 1))
    .map(([month, v]) => ({ month, ...v, net: v.income - v.expense }));
}

/**
 * Back-calculate net-worth month by month from transactions + holdings
 * historical prices + property/physical valuations. No manual snapshots.
 */
export function netWorthSeries(
  accounts: Account[],
  transactions: Transaction[],
  holdings: Holding[] = [],
  properties: Property[] = [],
  physical: PhysicalAsset[] = [],
  trades: Trade[] = [],
  fx: FxMap = {},
  base = "USD",
  fxHist: FxHistory = {},
): { month: string; value: number }[] {
  const now = totalNetWorth(accounts, holdings, properties, physical, fx, base);
  const cf = monthlyCashflow(transactions, fx, base, fxHist);
  if (cf.length === 0) return [];

  const monthPortfolio = (month: string) => {
    const asOf = `${month}-31`;
    let total = 0;
    for (const h of holdings) {
      const shares = trades.length ? sharesAt(trades, h.symbol, asOf) : h.shares;
      if (shares <= 0) continue;
      const pt = [...h.history].reverse().find((p) => p.date.slice(0, 7) <= month);
      const native = shares * (pt?.price ?? h.price);
      total += native * rateAtMonth(h.currency, month, fxHist, fx, base);
    }
    return total;
  };

  const monthProperty = (month: string) => {
    let total = 0;
    for (const p of properties) {
      if (p.purchaseDate.slice(0, 7) > month) continue;
      if (p.soldDate && p.soldDate.slice(0, 7) < month) continue;
      const v = [...p.valuations].reverse().find((x) => x.date.slice(0, 7) <= month);
      total += (v?.value ?? p.currentValue) * rateAtMonth(p.currency, month, fxHist, fx, base);
    }
    return total;
  };
  const monthPhysical = (month: string) => {
    let total = 0;
    for (const a of physical) {
      if (a.purchaseDate.slice(0, 7) > month) continue;
      if (a.soldDate && a.soldDate.slice(0, 7) < month) continue;
      total += a.currentValue * rateAtMonth(a.currency, month, fxHist, fx, base);
    }
    return total;
  };

  const series: { month: string; value: number }[] = [];
  let cash = netWorth(accounts, fx, base);
  for (let i = cf.length - 1; i >= 0; i--) {
    const m = cf[i].month;
    const val = cash + monthPortfolio(m) + monthProperty(m) + monthPhysical(m);
    series.unshift({ month: m, value: Math.round(val) });
    cash -= cf[i].net;
  }
  if (series.length)
    series[series.length - 1] = {
      month: series[series.length - 1].month,
      value: Math.round(now),
    };
  return series;
}

export function spendingByCategory(transactions: Transaction[], days = 30, fx: FxMap = {}, base = "USD") {
  const map = new Map<string, number>();
  const cutoff = new Date();
  cutoff.setDate(cutoff.getDate() - days);
  for (const t of transactions) {
    if (t.kind !== "expense") continue;
    if (new Date(t.date) < cutoff) continue;
    map.set(t.category, (map.get(t.category) ?? 0) + -toBase(t.amount, t.currency, fx, base));
  }
  return Array.from(map.entries())
    .map(([category, amount]) => ({ category, amount: Math.round(amount * 100) / 100 }))
    .sort((a, b) => b.amount - a.amount);
}

const SIDE_CATEGORIES = new Set([
  "side",
  "side income",
  "rental",
  "rent",
  "freelance",
  "hobby",
  "gig",
  "consulting",
  "royalty",
]);

export function isSideIncome(category: string) {
  return SIDE_CATEGORIES.has(category.toLowerCase());
}

export function incomeBySource(transactions: Transaction[], fx: FxMap = {}, base = "USD") {
  const map = new Map<string, number>();
  const cutoff = new Date();
  cutoff.setFullYear(cutoff.getFullYear() - 1);
  for (const t of transactions) {
    if (t.kind !== "income") continue;
    if (new Date(t.date) < cutoff) continue;
    map.set(t.category, (map.get(t.category) ?? 0) + toBase(t.amount, t.currency, fx, base));
  }
  return Array.from(map.entries())
    .map(([source, amount]) => ({ source, amount: Math.round(amount * 100) / 100 }))
    .sort((a, b) => b.amount - a.amount);
}

// ---- payers (income counterparties) ----

export function payerSlug(name: string) {
  return encodeURIComponent(name.trim().toLowerCase());
}

/** Every payer you have ever received income from, with totals. */
export function incomeByPayer(transactions: Transaction[]) {
  const map = new Map<string, { payer: string; total: number; count: number; last: string }>();
  for (const t of transactions) {
    if (t.kind !== "income") continue;
    const key = t.merchant.trim().toLowerCase();
    if (!key) continue;
    const cur = map.get(key) ?? { payer: t.merchant.trim(), total: 0, count: 0, last: t.date };
    cur.total += t.amount;
    cur.count += 1;
    if (t.date > cur.last) cur.last = t.date;
    map.set(key, cur);
  }
  return Array.from(map.values()).sort((a, b) => b.total - a.total);
}

export function payerTransactions(transactions: Transaction[], payer: string) {
  const key = decodeURIComponent(payer).trim().toLowerCase();
  return transactions
    .filter((t) => t.kind === "income" && t.merchant.trim().toLowerCase() === key)
    .sort((a, b) => (a.date < b.date ? 1 : -1));
}

export function monthlyTotals(transactions: Transaction[]) {
  const map = new Map<string, number>();
  for (const t of transactions) map.set(monthKey(t.date), (map.get(monthKey(t.date)) ?? 0) + t.amount);
  return Array.from(map.entries())
    .sort(([a], [b]) => (a < b ? -1 : 1))
    .map(([month, amount]) => ({ month, amount: Math.round(amount * 100) / 100 }));
}

// ---- recurrence ----

export function advance(date: string, every: number, unit: RecurUnit) {
  const d = new Date(`${date}T00:00:00Z`);
  if (unit === "day") d.setUTCDate(d.getUTCDate() + every);
  else if (unit === "week") d.setUTCDate(d.getUTCDate() + every * 7);
  else d.setUTCMonth(d.getUTCMonth() + every);
  return d.toISOString().slice(0, 10);
}

/** Dates a rule should have fired on, up to and including `until`. */
export function dueDates(rule: RecurringRule, until: string): string[] {
  if (!rule.active) return [];
  const out: string[] = [];
  let d = rule.lastRun ? advance(rule.lastRun, rule.every, rule.unit) : rule.startDate;
  let guard = 0;
  while (d <= until && guard++ < 500) {
    if (rule.endDate && d > rule.endDate) break;
    out.push(d);
    d = advance(d, rule.every, rule.unit);
  }
  return out;
}

export function describeRule(rule: RecurringRule) {
  const n = rule.every;
  const unit = n === 1 ? rule.unit : `${rule.unit}s`;
  return n === 1 ? `every ${rule.unit}` : `every ${n} ${unit}`;
}

export function savingsRateSeries(transactions: Transaction[], fx: FxMap = {}, base = "USD", fxHist: FxHistory = {}) {
  return monthlyCashflow(transactions, fx, base, fxHist).map((m) => ({
    month: m.month,
    rate:
      m.income > 0
        ? Math.max(0, Math.round(((m.income - m.expense) / m.income) * 1000) / 10)
        : 0,
  }));
}

export function assetAllocation(
  holdings: Holding[],
  properties: Property[] = [],
  physical: PhysicalAsset[] = [],
  fx: FxMap = {},
  base = "USD",
  accounts: Account[] = [],
) {
  const map = new Map<string, number>();
  for (const h of holdings) {
    const v = toBase(h.shares * h.price, h.currency, fx, base);
    map.set(h.assetClass, (map.get(h.assetClass) ?? 0) + v);
  }
  const fxCash = accounts
    .filter((a) => a.currency !== base && a.balance > 0)
    .reduce((s, a) => s + toBase(a.balance, a.currency, fx, base), 0);
  if (fxCash > 0) map.set("forex", (map.get("forex") ?? 0) + fxCash);
  const pv = propertyValue(properties, fx, base);
  if (pv > 0) map.set("property", pv);
  const ph = physicalValue(physical, fx, base);
  if (ph > 0) map.set("physical", ph);
  return Array.from(map.entries()).map(([k, v]) => ({ name: k, value: Math.round(v) }));
}

/** Currency used when a caller doesn't pass one — kept in sync with settings. */
let displayCurrency = "AUD";
export function setDisplayCurrency(code: string) {
  if (code) displayCurrency = code;
}

export function fmtCurrency(
  n: number,
  opts: { compact?: boolean; currency?: string } = {},
) {
  const currency = opts.currency ?? displayCurrency;
  const safe = (c: string) => {
    try {
      new Intl.NumberFormat("en-US", { style: "currency", currency: c }).format(1);
      return c;
    } catch {
      return "USD";
    }
  };
  const cur = safe(currency);
  if (!isFinite(n))
    return new Intl.NumberFormat("en-US", { style: "currency", currency: cur, maximumFractionDigits: 0 }).format(0);
  if (opts.compact && Math.abs(n) >= 1000) {
    const abs = Math.abs(n);
    const sign = n < 0 ? "-" : "";
    const sym =
      new Intl.NumberFormat("en-US", { style: "currency", currency: cur, maximumFractionDigits: 0 })
        .formatToParts(0)
        .find((p) => p.type === "currency")?.value ?? "$";
    if (abs >= 1_000_000) return `${sign}${sym}${(abs / 1_000_000).toFixed(1)}M`;
    if (abs >= 1_000) return `${sign}${sym}${(abs / 1_000).toFixed(1)}K`;
  }
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: cur,
    maximumFractionDigits: 2,
  }).format(n);
}
export function fmtPct(n: number) {
  if (!isFinite(n)) return "0.00%";
  return `${n >= 0 ? "+" : ""}${n.toFixed(2)}%`;
}

// ---- trade-derived holdings ----

export interface SymbolMeta {
  name?: string;
  assetClass?: AssetClass;
  currency?: string;
  sector?: string;
}

/**
 * Holdings are never entered by hand — they are the running result of the
 * trade ledger. Average-cost basis in both the asset's currency and the base
 * currency (using the FX rate stored on each trade), so realized P/L includes
 * currency gain or loss.
 */
export function deriveHoldings(
  trades: Trade[],
  prev: Holding[] = [],
  meta: Record<string, SymbolMeta> = {},
): Holding[] {
  const sorted = [...trades]
    .filter((t) => t.assetClass !== "forex")
    .sort((a, b) => (a.date === b.date ? 0 : a.date < b.date ? -1 : 1));
  const acc = new Map<
    string,
    {
      shares: number;
      cost: number;
      costBase: number;
      realized: number;
      realizedBase: number;
      last: number;
      currency?: string;
    }
  >();

  for (const t of sorted) {
    const sym = t.symbol.toUpperCase();
    const cur =
      acc.get(sym) ??
      {
        shares: 0,
        cost: 0,
        costBase: 0,
        realized: 0,
        realizedBase: 0,
        last: t.price,
        currency: t.currency,
      };
    const extra = (t.fees || 0) + (t.tax ?? 0);
    const rate = t.fxRate && t.fxRate > 0 ? t.fxRate : 1;
    if (t.side === "buy") {
      cur.shares += t.shares;
      cur.cost += t.shares * t.price + extra;
      cur.costBase += (t.shares * t.price + extra) * rate;
    } else {
      const avg = cur.shares > 0 ? cur.cost / cur.shares : t.price;
      const avgBase = cur.shares > 0 ? cur.costBase / cur.shares : t.price * rate;
      const qty = Math.min(t.shares, cur.shares);
      cur.realized += qty * (t.price - avg) - extra;
      cur.realizedBase += (qty * t.price - extra) * rate - qty * avgBase;
      cur.shares = Math.max(0, cur.shares - t.shares);
      cur.cost = Math.max(0, cur.cost - qty * avg);
      cur.costBase = Math.max(0, cur.costBase - qty * avgBase);
    }
    cur.last = t.price;
    cur.currency = t.currency ?? cur.currency;
    acc.set(sym, cur);
  }

  const out: Holding[] = [];
  for (const [symbol, v] of acc) {
    const old = prev.find((h) => h.symbol === symbol);
    const m = meta[symbol] ?? {};
    out.push({
      id: old?.id ?? symbol,
      symbol,
      name: m.name || old?.name || symbol,
      assetClass: m.assetClass ?? old?.assetClass ?? "stock",
      shares: Math.round(v.shares * 1e8) / 1e8,
      avgCost: v.shares > 0 ? v.cost / v.shares : 0,
      avgCostBase: v.shares > 0 ? v.costBase / v.shares : 0,
      price: old?.price && old.price > 0 ? old.price : v.last,
      dayChangePct: old?.dayChangePct ?? 0,
      sector: m.sector ?? old?.sector,
      currency: m.currency ?? old?.currency ?? v.currency,
      priceUpdatedAt: old?.priceUpdatedAt,
      realized: Math.round(v.realized * 100) / 100,
      realizedBase: Math.round(v.realizedBase * 100) / 100,
      history: old?.history ?? [],
    });
  }
  return out.filter((h) => h.shares > 0.00000001 || (h.realizedBase ?? 0) !== 0);
}

/** Shares of `symbol` held on (or before) an ISO date, from the ledger. */
export function sharesAt(trades: Trade[], symbol: string, date: string) {
  let shares = 0;
  for (const t of trades) {
    if (t.assetClass === "forex") continue;
    if (t.symbol.toUpperCase() !== symbol.toUpperCase()) continue;
    if (t.date > date) continue;
    shares += t.side === "buy" ? t.shares : -t.shares;
  }
  return Math.max(0, shares);
}

/** Historical close for a symbol at/just before a date, falling back to live price. */
export function priceAt(holding: Holding, date: string) {
  const pt = [...holding.history].reverse().find((p) => p.date <= date);
  return pt?.price ?? holding.price;
}

/** Portfolio market value at any past date: ledger shares × historical close. */
export function portfolioValueAt(
  holdings: Holding[],
  trades: Trade[],
  date: string,
  fx: FxMap = {},
  base = "USD",
  fxHist: FxHistory = {},
) {
  let total = 0;
  for (const h of holdings) {
    const q = sharesAt(trades, h.symbol, date);
    if (q <= 0) continue;
    total += q * priceAt(h, date) * rateAtMonth(h.currency, date.slice(0, 7), fxHist, fx, base);
  }
  return total;
}

/** Realized P/L booked across all closed positions, in base currency. */
export function realizedPL(holdings: Holding[]) {
  return holdings.reduce((s, h) => s + (h.realizedBase ?? h.realized ?? 0), 0);
}
