/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PropertyRouteImport } from './routes/property'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as OtherAssetsRouteImport } from './routes/other-assets'
import { Route as NetWorthRouteImport } from './routes/net-worth'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as InvestmentsRouteImport } from './routes/investments'
import { Route as IncomeRouteImport } from './routes/income'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as DividendsRouteImport } from './routes/dividends'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvestmentsSymbolRouteImport } from './routes/investments.$symbol'
import { Route as AuthConfirmedRouteImport } from './routes/auth.confirmed'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyRoute = PropertyRouteImport.update({
  id: '/property',
  path: '/property',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const OtherAssetsRoute = OtherAssetsRouteImport.update({
  id: '/other-assets',
  path: '/other-assets',
  getParentRoute: () => rootRouteImport,
} as any)
const NetWorthRoute = NetWorthRouteImport.update({
  id: '/net-worth',
  path: '/net-worth',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentsRoute = InvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomeRoute = IncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const DividendsRoute = DividendsRouteImport.update({
  id: '/dividends',
  path: '/dividends',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentsSymbolRoute = InvestmentsSymbolRouteImport.update({
  id: '/$symbol',
  path: '/$symbol',
  getParentRoute: () => InvestmentsRoute,
} as any)
const AuthConfirmedRoute = AuthConfirmedRouteImport.update({
  id: '/auth/confirmed',
  path: '/auth/confirmed',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/budget': typeof BudgetRoute
  '/dividends': typeof DividendsRoute
  '/expenses': typeof ExpensesRoute
  '/goals': typeof GoalsRoute
  '/guide': typeof GuideRoute
  '/income': typeof IncomeRoute
  '/investments': typeof InvestmentsRouteWithChildren
  '/markets': typeof MarketsRoute
  '/net-worth': typeof NetWorthRoute
  '/other-assets': typeof OtherAssetsRoute
  '/portfolio': typeof PortfolioRoute
  '/property': typeof PropertyRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/auth/confirmed': typeof AuthConfirmedRoute
  '/investments/$symbol': typeof InvestmentsSymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/budget': typeof BudgetRoute
  '/dividends': typeof DividendsRoute
  '/expenses': typeof ExpensesRoute
  '/goals': typeof GoalsRoute
  '/guide': typeof GuideRoute
  '/income': typeof IncomeRoute
  '/investments': typeof InvestmentsRouteWithChildren
  '/markets': typeof MarketsRoute
  '/net-worth': typeof NetWorthRoute
  '/other-assets': typeof OtherAssetsRoute
  '/portfolio': typeof PortfolioRoute
  '/property': typeof PropertyRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/auth/confirmed': typeof AuthConfirmedRoute
  '/investments/$symbol': typeof InvestmentsSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/budget': typeof BudgetRoute
  '/dividends': typeof DividendsRoute
  '/expenses': typeof ExpensesRoute
  '/goals': typeof GoalsRoute
  '/guide': typeof GuideRoute
  '/income': typeof IncomeRoute
  '/investments': typeof InvestmentsRouteWithChildren
  '/markets': typeof MarketsRoute
  '/net-worth': typeof NetWorthRoute
  '/other-assets': typeof OtherAssetsRoute
  '/portfolio': typeof PortfolioRoute
  '/property': typeof PropertyRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/auth/confirmed': typeof AuthConfirmedRoute
  '/investments/$symbol': typeof InvestmentsSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/budget'
    | '/dividends'
    | '/expenses'
    | '/goals'
    | '/guide'
    | '/income'
    | '/investments'
    | '/markets'
    | '/net-worth'
    | '/other-assets'
    | '/portfolio'
    | '/property'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/transactions'
    | '/auth/confirmed'
    | '/investments/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/budget'
    | '/dividends'
    | '/expenses'
    | '/goals'
    | '/guide'
    | '/income'
    | '/investments'
    | '/markets'
    | '/net-worth'
    | '/other-assets'
    | '/portfolio'
    | '/property'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/transactions'
    | '/auth/confirmed'
    | '/investments/$symbol'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/budget'
    | '/dividends'
    | '/expenses'
    | '/goals'
    | '/guide'
    | '/income'
    | '/investments'
    | '/markets'
    | '/net-worth'
    | '/other-assets'
    | '/portfolio'
    | '/property'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/transactions'
    | '/auth/confirmed'
    | '/investments/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  BudgetRoute: typeof BudgetRoute
  DividendsRoute: typeof DividendsRoute
  ExpensesRoute: typeof ExpensesRoute
  GoalsRoute: typeof GoalsRoute
  GuideRoute: typeof GuideRoute
  IncomeRoute: typeof IncomeRoute
  InvestmentsRoute: typeof InvestmentsRouteWithChildren
  MarketsRoute: typeof MarketsRoute
  NetWorthRoute: typeof NetWorthRoute
  OtherAssetsRoute: typeof OtherAssetsRoute
  PortfolioRoute: typeof PortfolioRoute
  PropertyRoute: typeof PropertyRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  TransactionsRoute: typeof TransactionsRoute
  AuthConfirmedRoute: typeof AuthConfirmedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property': {
      id: '/property'
      path: '/property'
      fullPath: '/property'
      preLoaderRoute: typeof PropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/other-assets': {
      id: '/other-assets'
      path: '/other-assets'
      fullPath: '/other-assets'
      preLoaderRoute: typeof OtherAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/net-worth': {
      id: '/net-worth'
      path: '/net-worth'
      fullPath: '/net-worth'
      preLoaderRoute: typeof NetWorthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments': {
      id: '/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof InvestmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/income': {
      id: '/income'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof IncomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dividends': {
      id: '/dividends'
      path: '/dividends'
      fullPath: '/dividends'
      preLoaderRoute: typeof DividendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments/$symbol': {
      id: '/investments/$symbol'
      path: '/$symbol'
      fullPath: '/investments/$symbol'
      preLoaderRoute: typeof InvestmentsSymbolRouteImport
      parentRoute: typeof InvestmentsRoute
    }
    '/auth/confirmed': {
      id: '/auth/confirmed'
      path: '/auth/confirmed'
      fullPath: '/auth/confirmed'
      preLoaderRoute: typeof AuthConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InvestmentsRouteChildren {
  InvestmentsSymbolRoute: typeof InvestmentsSymbolRoute
}

const InvestmentsRouteChildren: InvestmentsRouteChildren = {
  InvestmentsSymbolRoute: InvestmentsSymbolRoute,
}

const InvestmentsRouteWithChildren = InvestmentsRoute._addFileChildren(
  InvestmentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  BudgetRoute: BudgetRoute,
  DividendsRoute: DividendsRoute,
  ExpensesRoute: ExpensesRoute,
  GoalsRoute: GoalsRoute,
  GuideRoute: GuideRoute,
  IncomeRoute: IncomeRoute,
  InvestmentsRoute: InvestmentsRouteWithChildren,
  MarketsRoute: MarketsRoute,
  NetWorthRoute: NetWorthRoute,
  OtherAssetsRoute: OtherAssetsRoute,
  PortfolioRoute: PortfolioRoute,
  PropertyRoute: PropertyRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  TransactionsRoute: TransactionsRoute,
  AuthConfirmedRoute: AuthConfirmedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
